linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gomnd
    - nlreturn
    - wsl
    # TODO: maybe re-enable these
    - exhaustruct
    - godox
    - varnamelen
    # TODO: fix error handling
    - goerr113
    - wrapcheck
    - errorlint
    - errname

    # Deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

linters-settings:
  cyclop:
    max-complexity: 15
  govet:
    check-shadowing: true
  gci:
    local-prefixes: gopkg.in/irc.v4
